version: 0.2
Phases:
  install:
    commands:
    - mkdir -p $DOMAIN/$APIKEY
    - cd /$DOMAIN/$APIKEY
    - find /$DOMAIN/$APIKEY -type f -exec sed -i -e s/NMA001/$APIKEY/g {} \;
    - find /$DOMAIN/$APIKEY -type f -exec sed -i -e s/3BY1VNMA001fwpD/$CLIENT_ID/g {} \;
    - find /$DOMAIN/$APIKEY -type f -exec sed -i -e s/nxuuMLYGMb92VWI3R62ff9e7f3916a/$SECRET_KEY/g {} \;
    - find /$DOMAIN/$APIKEY -type f -exec sed -i -e s#https://nextmoney.co.in/nextmoney#$CLIENT_APK_LINK#g {} \;
    - find /$DOMAIN/$APIKEY -type f -exec sed -i -e s#https://vitefintech.com/nextpay#$CLIENT_APK_LINK#g {} \;
    - cd /$DOMAIN/$APIKEY
    - tar -zcvf $APIKEY.tar.gz mainapk 
    - rm -r mainapk
artifacts:
  files:
    - '**/*'
