
version: 0.2
Phases:
  install:
    commands:
    - find -type f -exec sed -i -e s/NMA001/$API_KEY/g {} \;
    - find -type f -exec sed -i -e s/3BY1VNMA001fwpD/$CLIENT_ID/g {} \;
    - find -type f -exec sed -i -e s/nxuuMLYGMb92VWI3R62ff9e7f3916a/$SECRET_KEY/g {} \;
    - find -type f -exec sed -i -e s#https://nextmoney.co.in/nextmoney#$CLIENT_APK_LINK#g {} \;
    - find -type f -exec sed -i -e s#https://vitefintech.com/nextpay#$CLIENT_APK_LINK#g {} \;
    - rm buildspec.yml
    - rm -r software
artifacts:
  files:
    - '**/*'