version: 0.2
Phases:
  Build:
    commands:
    - mkdir -p /var/www/html/{{ssm:DOMAIN}}/{{API_KEY}}
    - cp -r /home/ubuntu/mainapk /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}}
    - cd /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}}
    - find /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}} -type f -exec sed -i -e s/NMA001/{{ssm:API_KEY}}/g {} \;
    - find /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}} -type f -exec sed -i -e s/3BY1VNMA001fwpD/{{ssm:CLIENT_ID}}/g {} \;
    - find /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}} -type f -exec sed -i -e s/nxuuMLYGMb92VWI3R62ff9e7f3916a/{{ssm:SECRET_KEY}}/g {} \;
    - find /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}} -type f -exec sed -i -e s#https://nextmoney.co.in/nextmoney#{{ssm:CLIENT_APK_LINK}}#g {} \;
    - find /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}} -type f -exec sed -i -e s#https://vitefintech.com/nextpay#{{ssm:CLIENT_APK_LINK}}#g {} \;
    - cd /var/www/html/{{ssm:DOMAIN}}/{{ssm:API_KEY}}
    - tar -zcvf {{ssm:API_KEY}}.tar.gz mainapk
    - rm -r mainapk
artifacts:
  files:
    - '**/*'
