version: 0.2
Phases:
  install:
    commands:
    - cd .. 
    - mkdir -p $DOMAIN/$API_KEY
    - cp -r mainapk $DOMAIN/$API_KEY
    - find /$DOMAIN/$API_KEY -type f -exec sed -i -e s/NMA001/$API_KEY/g {} \;
    - find /$DOMAIN/$API_KEY -type f -exec sed -i -e s/3BY1VNMA001fwpD/$CLIENT_ID/g {} \;
    - find /$DOMAIN/$API_KEY -type f -exec sed -i -e s/nxuuMLYGMb92VWI3R62ff9e7f3916a/$SECRET_KEY/g {} \;
    - find /$DOMAIN/$API_KEY -type f -exec sed -i -e s#https://nextmoney.co.in/nextmoney#$CLIENT_APK_LINK#g {} \;
    - find /$DOMAIN/$API_KEY -type f -exec sed -i -e s#https://vitefintech.com/nextpay#$CLIENT_APK_LINK#g {} \;
    - cd /$DOMAIN/$API_KEY
    - tar -zcvf $API_KEY.tar.gz mainapk 
    - rm -r mainapk
artifacts:
  files:
    - '**/*'
