version: 0.2
os: linux
files:
  - source: /
    destination: /home/ubuntu/mainapk/
Phase:
  Install:
    commands:
      - cd /home/ubuntu/mainapk/
      - chmod u+x apk.sh
  Build:
    commands:
      - ./apk.sh
artifacts:
  files:
    - '**/*'      

      
    
